name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: npx --yes awesome-lint@2.3.0
